version: "3.8"

services:
  mongo5:
    image: mongo:5
    container_name: mongo5
    platform: darwin/arm64
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /ssl/mongodb.key
        chown 999:999 /ssl/mongodb.key
        exec docker-entrypoint.sh $$@
    command: [
      "mongod",
      "--bind_ip_all",
      "--port", "10000",
      "--keyFile", "/ssl/mongodb.key",
      "--wiredTigerCacheSizeGB", "2",
    ]
    volumes:
      - ~/.ssh/:/ssl/
    environment:
      TZ: ETC/UTC
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev2301
    ports:
      - "10000:10000"
    networks:
      - dev
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
  mysql8:
    image: mysql:8.0.33
    container_name: mysql8
    platform: darwin/arm64
    environment:
      TZ: ETC/UTC
      MYSQL_ROOT_PASSWORD: dev2301
    ports:
      - "10001:3306"
    networks:
      - dev
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m

networks:
  dev:
    driver: bridge
    internal: false
